[package]
name = "upload_to_m100"
version = "0.1.0"
authors = ["Erik van der Tier <mail@erikvandertier.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
ascii = "1.0"